@baseURL = http://localhost:5201

### Get all Books

GET {{baseURL}}/api/books


### Create Book
POST {{baseURL}}/api/books
Content-Type: application/json

{
    "title" : "Clean-Code",
    "description" : "This book about writing clean and clear code to easy to maintain and read",
    "Year" : -1,
    "authorId" : "5c5d4d0e-3966-4d13-858c-bad032bceb1f"
}

### Create Book
POST {{baseURL}}/api/books
Content-Type: application/json

{
    "title" : "Clean-Architecture",
    "description" : "This book about writing a Code with A layered Architecture",
    "Year" : -1,
    "authorId" : "7d055109-b708-46fc-bd09-1014f0c2fae4"
}
### Create Author

POST {{baseURL}}/api/authors
Content-Type: application/json

{
    "name" : "John Smith"
}

### Create Author
POST {{baseURL}}/api/authors
Content-Type: application/json

{
    "name" : "Ahmed Shawki"
}


### Create Author
# POST {{baseURL}}/api/authors
# Content-Type: application/json

# {
#     "name" : ""
# }

### Get all Authors 
GET {{baseURL}}/api/authors

















###

POST {{baseURL}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "12345"
}

###
GET {{baseURL}}/api/auth/me

###
POST {{baseURL}}/api/auth/logout

###
GET {{baseURL}}/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBzbWFydGxpYnJhcnkuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODM4NDQxNjEsImlzcyI6IlNtYXJ0TGlicmFyeSIsImF1ZCI6IlNtYXJ0TGlicmFyeS5BUEkifQ.xO5Cltbm4HSFjMWfPPmWvnXJGueff8VNVRPi9_Bdaf4
